KAFKA_SERVER: your_kafka_address

KAFKA_USERNAME: your_kafka_username

KAFKA_PASSWORD: your_kafka_password

MILVUS_URI: your_milvus_uri

MILVUS_TOKEN: your_milvus_token

KAFKA_REPLICATION_FACTOR: 3 # 3 required for conflunet cloud

EMBEDDING_MODEL: BAAI/bge-small-en-v1.5 # Huggingface sentence transformer model to use
EMBEDDING_DIM: 384 # Output dimension of model

OPENAI_KEY: your_api
